# Generated by Django 4.1.3 on 2022-11-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, verbose_name='owner')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.CharField(max_length=10, verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('year', models.CharField(max_length=4, verbose_name='year')),
                ('publisher', models.CharField(max_length=50, verbose_name='publisher')),
                ('image', models.ImageField(upload_to='images/', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
