# Generated by Django 3.2.6 on 2022-11-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ownerscontact',
            field=models.CharField(max_length=50, null=True, verbose_name='ownerscontact'),
        ),
    ]
